LANGUAGE_LIST = {
    1: "Chinese (Mandarin))",
    2: "Spanish",
    3: "English",
    4: "Hindi",
    5: "Arabic",
    6: "Portuguese",
    7: "Bengali",
    8: "Russian",
    9: "Japanese",
    10: "Punjabi",
    11: "German",
    12: "Javanese",
    13: "Wu (Shanghainese)",
    14: "Malay/Indonesian",
    15: "Telugu",
    16: "Vietnamese",
    17: "Korean",
    18: "French",
    19: "Tamil",
    20: "Marathi",
    21: "Turkish",
    22: "Urdu",
    23: "Italian",
    24: "Thai",
    25: "Gujarati",
    26: "Jin (Shanxi Chinese)",
    27: "Kannada",
    28: "Egyptian Arabic",
    29: "Polish",
    30: "Ukrainian",
    31: "Igbo",
    32: "Xhosa",
    33: "Tagalog",
    34: "Amharic",
    35: "Farsi (Persian)",
    36: "Romanian",
    37: "Odia (Oriya)",
    38: "Sindhi",
    39: "Nepali",
    40: "Greek",
    41: "Bulgarian",
    42: "Hebrew",
    43: "Hungarian",
    44: "Swedish",
    45: "Hausa",
    46: "Azerbaijani",
    47: "Czech",
    48: "Kinyarwanda",
    49: "Dutch",
    50: "Haitian Creole",
}