# Generated by Django 5.1.1 on 2024-10-09 21:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.IntegerField(choices=[(1, 'Chinese (Mandarin))'), (2, 'Spanish'), (3, 'English'), (4, 'Hindi'), (5, 'Arabic'), (6, 'Portuguese'), (7, 'Bengali'), (8, 'Russian'), (9, 'Japanese'), (10, 'Punjabi'), (11, 'German'), (12, 'Javanese'), (13, 'Wu (Shanghainese)'), (14, 'Malay/Indonesian'), (15, 'Telugu'), (16, 'Vietnamese'), (17, 'Korean'), (18, 'French'), (19, 'Tamil'), (20, 'Marathi'), (21, 'Turkish'), (22, 'Urdu'), (23, 'Italian'), (24, 'Thai'), (25, 'Gujarati'), (26, 'Jin (Shanxi Chinese)'), (27, 'Kannada'), (28, 'Egyptian Arabic'), (29, 'Polish'), (30, 'Ukrainian'), (31, 'Igbo'), (32, 'Xhosa'), (33, 'Tagalog'), (34, 'Amharic'), (35, 'Farsi (Persian)'), (36, 'Romanian'), (37, 'Odia (Oriya)'), (38, 'Sindhi'), (39, 'Nepali'), (40, 'Greek'), (41, 'Bulgarian'), (42, 'Hebrew'), (43, 'Hungarian'), (44, 'Swedish'), (45, 'Hausa'), (46, 'Azerbaijani'), (47, 'Czech'), (48, 'Kinyarwanda'), (49, 'Dutch'), (50, 'Haitian Creole')])),
                ('picture', models.FileField(upload_to='media_platform\\picture')),
                ('sub_channels', models.ManyToManyField(blank=True, to='media_platform.channel')),
                ('content', models.ManyToManyField(blank=True, to='media_platform.content')),
            ],
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='media_platform\\content')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='media_platform.content')),
            ],
        ),
        migrations.CreateModel(
            name='ContentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='media_platform.content')),
            ],
        ),
    ]
