# Generated by Django 5.1.1 on 2024-10-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='groups',
            field=models.ManyToManyField(blank=True, to='media_platform.group'),
        ),
    ]
