name: Django TEST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMMFLYTEST_DJANGO_KEY: ${{ secrets.IMMFLYTEST_DJANGO_KEY }}

jobs:
  build:
    runs-on: python:3.12-alpine3.20

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
